### ISSUE TITLE
url issue again

### ISSUE THREAD

**Issue by dranjor** [fa-ribeiro/dokuwiki-plugin-socialite#11]
I want to use socialite within my blog using the [blog-plugin](https://www.dokuwiki.org/plugin:blog). Blog posts are included by the main blog page.  Socialite generate a url of the main page but not the url of the article page.

**Comment by fa-ribeiro** [comment]
The idea behind socialite is to generates links to current page only.
However, if you add socialite to you blog post page it will generate links to your posts.
