### ISSUE TITLE
Incorrect metatada?

### ISSUE THREAD

**Issue by powerslave** [fa-ribeiro/dokuwiki-plugin-socialite#12]
1. In dokuwiki plugin page, title reads `Locialite`. Typo?
    * https://github.com/fa-ribeiro/dokuwiki-plugin-socialite/blob/master/plugin.info.txt#L5
1. _New version available_ is shown, right after fresh install. Also, `Update` does not make the message go away.

![image](https://user-images.githubusercontent.com/853599/33396841-147acfca-d54a-11e7-92ba-c5eb984216c4.png)

**Comment by fa-ribeiro** [comment]
Correct plugin description (30cc6ef)
