### ISSUE TITLE
Automatically add socialite on all pages?

### ISSUE THREAD

**Issue by karnhack** [fa-ribeiro/dokuwiki-plugin-socialite#17]
is it possible to insert socialite on all pages automatically?
Thanks

**Comment by fa-ribeiro** [comment]
You can use several options to achieve this:
* use theme supporting personalized header/footer/sidebar pages, plugin page includes
* change our theme header/footer
* use a plugin to include a block on every page
* ...

**Comment by vaniwiki** [comment]
I am using the latest DokuWiki with Bootie theme. When inserting socialite in either sidebar or footer, it only shares the sidebar and footer pages, no matter what page I'm on. I am using `~~NOCACHE~~`.
