### ISSUE TITLE
Make usable in sidebar/footer

### ISSUE THREAD

**Issue by vaniwiki** [fa-ribeiro/dokuwiki-plugin-socialite#19]
When inserting socialite in either sidebar or footer, it only shares the sidebar and footer pages, no matter what page I'm on. I am using `~~NOCACHE~~`.

_Originally posted by @ahaituki in https://github.com/fa-ribeiro/dokuwiki-plugin-socialite/issues/17#issuecomment-445431839_

**Comment by fa-ribeiro** [comment]
should be fixed now with commit 7c7c58ac
@ahaituki, can you please test now and share the results?

**Comment by vaniwiki** [comment]
Works perfect! 👌 You can see it in action on https://prabhupada.io
