### ISSUE TITLE
Icons in Firefox

### ISSUE THREAD

**Issue by chtiland** [fa-ribeiro/dokuwiki-plugin-socialite#2]
Icons doesn't display in Firefox, probably due to .ico format.
Why don't you use png format ?

**Comment by moijafcor** [comment]
+1

**Comment by fa-ribeiro** [comment]
@chtiland , @moijafcor 

icons changed to svg format. can you please check if it's working now?

tia

**Comment by fa-ribeiro** [comment]
socialite isn't using .ico anymore
