### ISSUE TITLE
Error: "Can't use method return value in write context"

### ISSUE THREAD

**Issue by JomiliDesign** [fa-ribeiro/dokuwiki-plugin-socialite#6]
Hi there,

after the installation (manually and auto) I got this error:
Can't use method return value in write context
Line: 132 and 166
File: syntax/buttons.php
Link: http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context

I've moved the function calls in 132 and 166 to a temp value and it worked.

Regards,
SkullbocksDE

**Comment by moijafcor** [comment]
Hi. Please take a look at the comments: https://www.dokuwiki.org/plugin:socialite#discussion 

Thanks

**Comment by fa-ribeiro** [comment]
fixed :-)
